	SpeedPlayerText[playerid][0] = CreatePlayerTextDraw(playerid, 568.750366, 363.481414, "INFERNUS");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][0], 0.139583, 0.977778);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][0], 2);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][0], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][0], 513);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid, SpeedPlayerText[playerid][0], 51);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][0], 2);
	PlayerTextDrawSetProportional(playerid, SpeedPlayerText[playerid][0], 1);

	SpeedPlayerText[playerid][1] = CreatePlayerTextDraw(playerid, 517.916503, 379.555541, "hud:radar_modGarage");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][1], 0.003333, 0.041481);
	PlayerTextDrawTextSize(playerid, SpeedPlayerText[playerid][1], 9.583376, 6.740758);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][1], 1);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][1], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][1], 0);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][1], 4);

	SpeedPlayerText[playerid][2] = CreatePlayerTextDraw(playerid, 540.166870, 377.444427, "1000 HP");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][2], 0.139583, 0.977778);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][2], 2);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][2], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][2], 513);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid, SpeedPlayerText[playerid][2], 51);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][2], 2);
	PlayerTextDrawSetProportional(playerid, SpeedPlayerText[playerid][2], 1);

	SpeedPlayerText[playerid][3] = CreatePlayerTextDraw(playerid, 518.333374, 387.851928, "hud:radar_impound");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][3], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, SpeedPlayerText[playerid][3], 9.166644, 9.851852);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][3], 1);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][3], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][3], 0);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][3], 0);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][3], 4);

	SpeedPlayerText[playerid][4] = CreatePlayerTextDraw(playerid, 542.000244, 388.296325, "150 KM/H");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][4], 0.139583, 0.977778);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][4], 2);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][4], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][4], 513);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][4], 0);
	PlayerTextDrawBackgroundColor(playerid, SpeedPlayerText[playerid][4], 51);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][4], 2);
	PlayerTextDrawSetProportional(playerid, SpeedPlayerText[playerid][4], 1);

	SpeedPlayerText[playerid][5] = CreatePlayerTextDraw(playerid, 514.166748, 399.777832, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][5], 0.055000, 0.057036);
	PlayerTextDrawTextSize(playerid, SpeedPlayerText[playerid][5], 15.833325, 11.925939);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][5], 1);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][5], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][5], 0);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][5], 0);
	PlayerTextDrawBackgroundColor(playerid, SpeedPlayerText[playerid][5], 0);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][5], 5);
	PlayerTextDrawSetProportional(playerid, SpeedPlayerText[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][5], 0);
	PlayerTextDrawSetPreviewModel(playerid, SpeedPlayerText[playerid][5], 1650);
	PlayerTextDrawSetPreviewRot(playerid, SpeedPlayerText[playerid][5], 0.000000, 0.000000, 0.000000, 1.000000);

	SpeedPlayerText[playerid][6] = CreatePlayerTextDraw(playerid, 534.666687, 400.703765, "150L");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][6], 0.139583, 0.977778);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][6], 2);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][6], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][6], 513);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][6], 0);
	PlayerTextDrawBackgroundColor(playerid, SpeedPlayerText[playerid][6], 51);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][6], 2);
	PlayerTextDrawSetProportional(playerid, SpeedPlayerText[playerid][6], 1);

	SpeedPlayerText[playerid][7] = CreatePlayerTextDraw(playerid, 601.500000, 376.814910, "engine");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][7], 0.139583, 0.977778);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][7], 2);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][7], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][7], 513);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][7], 0);
	PlayerTextDrawBackgroundColor(playerid, SpeedPlayerText[playerid][7], 51);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][7], 2);
	PlayerTextDrawSetProportional(playerid, SpeedPlayerText[playerid][7], 1);

	SpeedPlayerText[playerid][8] = CreatePlayerTextDraw(playerid, 613.750183, 378.518524, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][8], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, SpeedPlayerText[playerid][8], 5.833351, 6.740737);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][8], 1);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][8], 8388863);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][8], 0);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][8], 0);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][8], 4);

	SpeedPlayerText[playerid][9] = CreatePlayerTextDraw(playerid, 601.666687, 387.148315, "DOORS");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][9], 0.139583, 0.977778);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][9], 2);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][9], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][9], 513);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][9], 0);
	PlayerTextDrawBackgroundColor(playerid, SpeedPlayerText[playerid][9], 51);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][9], 2);
	PlayerTextDrawSetProportional(playerid, SpeedPlayerText[playerid][9], 1);

	SpeedPlayerText[playerid][10] = CreatePlayerTextDraw(playerid, 613.916870, 389.370422, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][10], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, SpeedPlayerText[playerid][10], 5.833351, 6.740737);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][10], 1);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][10], -16776961);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][10], 0);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][10], 0);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][10], 4);

	SpeedPlayerText[playerid][11] = CreatePlayerTextDraw(playerid, 601.416564, 398.000152, "lights");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][11], 0.139583, 0.977778);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][11], 2);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][11], -1);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][11], 513);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][11], 0);
	PlayerTextDrawBackgroundColor(playerid, SpeedPlayerText[playerid][11], 51);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][11], 2);
	PlayerTextDrawSetProportional(playerid, SpeedPlayerText[playerid][11], 1);

	SpeedPlayerText[playerid][12] = CreatePlayerTextDraw(playerid, 614.083496, 400.222290, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, SpeedPlayerText[playerid][12], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, SpeedPlayerText[playerid][12], 5.833351, 6.740737);
	PlayerTextDrawAlignment(playerid, SpeedPlayerText[playerid][12], 1);
	PlayerTextDrawColor(playerid, SpeedPlayerText[playerid][12], -16776961);
	PlayerTextDrawSetShadow(playerid, SpeedPlayerText[playerid][12], 0);
	PlayerTextDrawSetOutline(playerid, SpeedPlayerText[playerid][12], 0);
	PlayerTextDrawFont(playerid, SpeedPlayerText[playerid][12], 4);